ALTER TABLE profiles
ADD COLUMN profile_image_focus_x DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN profile_image_focus_y DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN profile_image_scale DOUBLE PRECISION NOT NULL DEFAULT 1;
